language: scala
jdk: openjdk8
script: sbt -batch ++${TRAVIS_SCALA_VERSION} test:compile testJVM/test mimaReportBinaryIssues
git:
  depth: false
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - scala: 2.10.7
  - scala: 2.11.12
  - scala: 2.12.4
  - scala: 2.13.0-M5
  - stage: release
    script: sbt ci-release
cache:
  directories:
  - $HOME/.cache
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
