language: scala
jdk: openjdk8
script: sbt -batch ++${TRAVIS_SCALA_VERSION} test:compile test mimaReportBinaryIssues
git:
  depth: false
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
  - scala: 2.12.13
  - scala: 2.13.3
  - stage: release
    script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.cache
  - $HOME/.coursier
  - $HOME/.ivy2/cache
  - $HOME/.sbt
